config/routes.rb
Rails.application.routes.draw do

  resources :profile_image_repeatables

  resources :profile_characteristic_repeatables

  resources :profile_basic_repeatables

  resources :profile_quotes

  resources :profile_scalers

  devise_for :users
  resources :packs do
    resources :profiles
  end

  root 'pages#index'
end

app/models/profile_quote.rb
class ProfileQuote < ActiveRecord::Base
  belongs_to :profile

  validates :quote, presence: true
end

app/controllers/profile_quotes_controller.rb
class ProfileQuotesController < ApplicationController
  before_action :set_profile_quote, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profile_quotes = ProfileQuote.all
    respond_with(@profile_quotes)
  end

  def show
    respond_with(@profile_quote)
  end

  def new
    @profile_quote = ProfileQuote.new
    respond_with(@profile_quote)
  end

  def edit
  end

  def create
    @profile_quote = ProfileQuote.new(profile_quote_params)
    @profile_quote.save
    respond_with(@profile_quote)
  end

  def update
    @profile_quote.update(profile_quote_params)
    respond_with(@profile_quote)
  end

  def destroy
    @profile_quote.destroy
    respond_with(@profile_quote)
  end

  private
    def set_profile_quote
      @profile_quote = ProfileQuote.find(params[:id])
    end

    def profile_quote_params
      params.require(:profile_quote).permit(:quote, :profile_id)
    end
end

app/helpers/profile_quotes_helper.rb
module ProfileQuotesHelper
end

app/views/profile_quotes/_form.html.haml
= form_for @profile_quote do |f|
  - if @profile_quote.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile_quote.errors.count, "error")} prohibited this profile_quote from being saved:"
      %ul
        - @profile_quote.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :quote
    = f.text_field :quote
  .field
    = f.label :profile
    = f.text_field :profile
  .actions
    = f.submit 'Save'

app/views/profile_quotes/edit.html.haml
%h1 Editing profile_quote

= render 'form'

= link_to 'Show', @profile_quote
\|
= link_to 'Back', profile_quotes_path

app/views/profile_quotes/index.html.haml
%h1 Listing profile_quotes

%table
  %thead
    %tr
      %th Quote
      %th Profile
      %th
      %th
      %th
      
  %tbody
    - @profile_quotes.each do |profile_quote|
      %tr
        %td= profile_quote.quote
        %td= profile_quote.profile
        %td= link_to 'Show', profile_quote
        %td= link_to 'Edit', edit_profile_quote_path(profile_quote)
        %td= link_to 'Destroy', profile_quote, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profile quote', new_profile_quote_path

app/views/profile_quotes/new.html.haml
%h1 New profile_quote

= render 'form'

= link_to 'Back', profile_quotes_path

app/views/profile_quotes/show.html.haml
%p#notice= notice

%p
  %b Quote:
  = @profile_quote.quote
%p
  %b Profile:
  = @profile_quote.profile

= link_to 'Edit', edit_profile_quote_path(@profile_quote)
\|
= link_to 'Back', profile_quotes_path