config/routes.rb
Rails.application.routes.draw do

  resources :profile_image_repeatables

  resources :profile_characteristic_repeatables

  resources :profile_basic_repeatables

  resources :profile_quotes

  resources :profile_scalers

  devise_for :users
  resources :packs do
    resources :profiles
  end

  root 'pages#index'
end

app/controllers/profile_basic_repeatables_controller.rb
class ProfileBasicRepeatablesController < ApplicationController
  before_action :set_profile_basic_repeatable, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profile_basic_repeatables = ProfileBasicRepeatable.all
    respond_with(@profile_basic_repeatables)
  end

  def show
    respond_with(@profile_basic_repeatable)
  end

  def new
    @profile_basic_repeatable = ProfileBasicRepeatable.new
    respond_with(@profile_basic_repeatable)
  end

  def edit
  end

  def create
    @profile_basic_repeatable = ProfileBasicRepeatable.new(profile_basic_repeatable_params)
    @profile_basic_repeatable.save
    respond_with(@profile_basic_repeatable)
  end

  def update
    @profile_basic_repeatable.update(profile_basic_repeatable_params)
    respond_with(@profile_basic_repeatable)
  end

  def destroy
    @profile_basic_repeatable.destroy
    respond_with(@profile_basic_repeatable)
  end

  private
    def set_profile_basic_repeatable
      @profile_basic_repeatable = ProfileBasicRepeatable.find(params[:id])
    end

    def profile_basic_repeatable_params
      params.require(:profile_basic_repeatable).permit(:name, :content, :profile_id)
    end
end

app/helpers/profile_basic_repeatables_helper.rb
module ProfileBasicRepeatablesHelper
end

app/views/profile_basic_repeatables/_form.html.haml
= form_for @profile_basic_repeatable do |f|
  - if @profile_basic_repeatable.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile_basic_repeatable.errors.count, "error")} prohibited this profile_basic_repeatable from being saved:"
      %ul
        - @profile_basic_repeatable.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :profile
    = f.text_field :profile
  .actions
    = f.submit 'Save'

app/views/profile_basic_repeatables/edit.html.haml
%h1 Editing profile_basic_repeatable

= render 'form'

= link_to 'Show', @profile_basic_repeatable
\|
= link_to 'Back', profile_basic_repeatables_path

app/views/profile_basic_repeatables/index.html.haml
%h1 Listing profile_basic_repeatables

%table
  %thead
    %tr
      %th Name
      %th Content
      %th Profile
      %th
      %th
      %th
      
  %tbody
    - @profile_basic_repeatables.each do |profile_basic_repeatable|
      %tr
        %td= profile_basic_repeatable.name
        %td= profile_basic_repeatable.content
        %td= profile_basic_repeatable.profile
        %td= link_to 'Show', profile_basic_repeatable
        %td= link_to 'Edit', edit_profile_basic_repeatable_path(profile_basic_repeatable)
        %td= link_to 'Destroy', profile_basic_repeatable, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profile basic repeatable', new_profile_basic_repeatable_path

app/views/profile_basic_repeatables/new.html.haml
%h1 New profile_basic_repeatable

= render 'form'

= link_to 'Back', profile_basic_repeatables_path

app/views/profile_basic_repeatables/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @profile_basic_repeatable.name
%p
  %b Content:
  = @profile_basic_repeatable.content
%p
  %b Profile:
  = @profile_basic_repeatable.profile

= link_to 'Edit', edit_profile_basic_repeatable_path(@profile_basic_repeatable)
\|
= link_to 'Back', profile_basic_repeatables_path