config/routes.rb
Rails.application.routes.draw do

  resources :profile_image_repeatables

  resources :profile_characteristic_repeatables

  resources :profile_basic_repeatables

  resources :profile_quotes

  resources :profile_scalers

  devise_for :users
  resources :packs do
    resources :profiles
  end

  root 'pages#index'
end

app/controllers/profile_characteristic_repeatables_controller.rb
class ProfileCharacteristicRepeatablesController < ApplicationController
  before_action :set_profile_characteristic_repeatable, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profile_characteristic_repeatables = ProfileCharacteristicRepeatable.all
    respond_with(@profile_characteristic_repeatables)
  end

  def show
    respond_with(@profile_characteristic_repeatable)
  end

  def new
    @profile_characteristic_repeatable = ProfileCharacteristicRepeatable.new
    respond_with(@profile_characteristic_repeatable)
  end

  def edit
  end

  def create
    @profile_characteristic_repeatable = ProfileCharacteristicRepeatable.new(profile_characteristic_repeatable_params)
    @profile_characteristic_repeatable.save
    respond_with(@profile_characteristic_repeatable)
  end

  def update
    @profile_characteristic_repeatable.update(profile_characteristic_repeatable_params)
    respond_with(@profile_characteristic_repeatable)
  end

  def destroy
    @profile_characteristic_repeatable.destroy
    respond_with(@profile_characteristic_repeatable)
  end

  private
    def set_profile_characteristic_repeatable
      @profile_characteristic_repeatable = ProfileCharacteristicRepeatable.find(params[:id])
    end

    def profile_characteristic_repeatable_params
      params.require(:profile_characteristic_repeatable).permit(:name, :content, :profile_id)
    end
end

app/helpers/profile_characteristic_repeatables_helper.rb
module ProfileCharacteristicRepeatablesHelper
end

app/views/profile_characteristic_repeatables/_form.html.haml
= form_for @profile_characteristic_repeatable do |f|
  - if @profile_characteristic_repeatable.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile_characteristic_repeatable.errors.count, "error")} prohibited this profile_characteristic_repeatable from being saved:"
      %ul
        - @profile_characteristic_repeatable.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :profile
    = f.text_field :profile
  .actions
    = f.submit 'Save'

app/views/profile_characteristic_repeatables/edit.html.haml
%h1 Editing profile_characteristic_repeatable

= render 'form'

= link_to 'Show', @profile_characteristic_repeatable
\|
= link_to 'Back', profile_characteristic_repeatables_path

app/views/profile_characteristic_repeatables/index.html.haml
%h1 Listing profile_characteristic_repeatables

%table
  %thead
    %tr
      %th Name
      %th Content
      %th Profile
      %th
      %th
      %th
      
  %tbody
    - @profile_characteristic_repeatables.each do |profile_characteristic_repeatable|
      %tr
        %td= profile_characteristic_repeatable.name
        %td= profile_characteristic_repeatable.content
        %td= profile_characteristic_repeatable.profile
        %td= link_to 'Show', profile_characteristic_repeatable
        %td= link_to 'Edit', edit_profile_characteristic_repeatable_path(profile_characteristic_repeatable)
        %td= link_to 'Destroy', profile_characteristic_repeatable, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profile characteristic repeatable', new_profile_characteristic_repeatable_path

app/views/profile_characteristic_repeatables/new.html.haml
%h1 New profile_characteristic_repeatable

= render 'form'

= link_to 'Back', profile_characteristic_repeatables_path

app/views/profile_characteristic_repeatables/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @profile_characteristic_repeatable.name
%p
  %b Content:
  = @profile_characteristic_repeatable.content
%p
  %b Profile:
  = @profile_characteristic_repeatable.profile

= link_to 'Edit', edit_profile_characteristic_repeatable_path(@profile_characteristic_repeatable)
\|
= link_to 'Back', profile_characteristic_repeatables_path