config/routes.rb
Rails.application.routes.draw do

  resources :profile_image_repeatables

  resources :profile_characteristic_repeatables

  resources :profile_basic_repeatables

  resources :profile_quotes

  resources :profile_scalers

  devise_for :users
  resources :packs do
    resources :profiles
  end

  root 'pages#index'
end

app/controllers/profile_image_repeatables_controller.rb
class ProfileImageRepeatablesController < ApplicationController
  before_action :set_profile_image_repeatable, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profile_image_repeatables = ProfileImageRepeatable.all
    respond_with(@profile_image_repeatables)
  end

  def show
    respond_with(@profile_image_repeatable)
  end

  def new
    @profile_image_repeatable = ProfileImageRepeatable.new
    respond_with(@profile_image_repeatable)
  end

  def edit
  end

  def create
    @profile_image_repeatable = ProfileImageRepeatable.new(profile_image_repeatable_params)
    @profile_image_repeatable.save
    respond_with(@profile_image_repeatable)
  end

  def update
    @profile_image_repeatable.update(profile_image_repeatable_params)
    respond_with(@profile_image_repeatable)
  end

  def destroy
    @profile_image_repeatable.destroy
    respond_with(@profile_image_repeatable)
  end

  private
    def set_profile_image_repeatable
      @profile_image_repeatable = ProfileImageRepeatable.find(params[:id])
    end

    def profile_image_repeatable_params
      params[:profile_image_repeatable]
    end
end

app/views/profile_image_repeatables/_form.html.haml
= form_for @profile_image_repeatable do |f|
  - if @profile_image_repeatable.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile_image_repeatable.errors.count, "error")} prohibited this profile_image_repeatable from being saved:"
      %ul
        - @profile_image_repeatable.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/profile_image_repeatables/edit.html.haml
%h1 Editing profile_image_repeatable

= render 'form'

= link_to 'Show', @profile_image_repeatable
\|
= link_to 'Back', profile_image_repeatables_path

app/views/profile_image_repeatables/index.html.haml
%h1 Listing profile_image_repeatables

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @profile_image_repeatables.each do |profile_image_repeatable|
      %tr
        %td= link_to 'Show', profile_image_repeatable
        %td= link_to 'Edit', edit_profile_image_repeatable_path(profile_image_repeatable)
        %td= link_to 'Destroy', profile_image_repeatable, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profile image repeatable', new_profile_image_repeatable_path

app/views/profile_image_repeatables/new.html.haml
%h1 New profile_image_repeatable

= render 'form'

= link_to 'Back', profile_image_repeatables_path

app/views/profile_image_repeatables/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_profile_image_repeatable_path(@profile_image_repeatable)
\|
= link_to 'Back', profile_image_repeatables_path